name: climax
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fw_ticket: ^0.1.1
  chewie: any
  barcode_flutter: ^1.1.2
  pigment: ^1.0.3
  ticket_card: ^0.2.0
  curved_navigation_bar: ^0.3.2
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.4
  flutter_icons: any
  google_sign_in: ^4.2.0
  google_fonts: ^0.3.9
  loading: ^1.0.2
  provider: ^4.0.4
  animated_splash: ^1.0.0
  flutter_ticket_widget: 
  simple_animations: ^1.3.9
  slimy_card: ^1.0.1
  tmdb_api: ^1.0.1-stable
  tmdb_dart: ^0.1.1
  video_player: ^0.10.8+1
  skeleton_text:
  transparent_image: ^1.0.0
  font_awesome_flutter: ^8.8.1
  animated_text_kit: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - locale/
  # fonts:
  #   - family: Ionicons
  #     fonts:
  #       - asset: fonts/Ionicons.ttf
  #   - family: AntDesign
  #     fonts:
  #       - asset: fonts/AntDesign.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
