name: climax
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fw_ticket: ^0.1.1
  chewie: any
  barcode_flutter: ^1.1.2
  curved_navigation_bar: ^0.3.2

  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  cloud_firestore: "^0.16.0+1"
  cloud_functions: "^0.9.0"
  firebase_storage: "^7.0.0"
  firebase_messaging: "^8.0.0-dev.15"
  flutter_facebook_auth: ^0.2.3

  flutter_icons: any
  flutter_ticket_widget: 
  font_awesome_flutter: ^8.8.1
  google_fonts: ^0.3.9
  google_sign_in: "^4.5.1"
  get: "^3.10.2"
  get_storage:
  loading: ^1.0.2
  logger: ^0.9.4
  provider: ^4.3.2+3
  material_design_icons_flutter: ^4.0.5755
  simple_animations: ^1.3.9
  pigment: ^1.0.3
  ticket_card: ^0.2.0
  slimy_card: ^1.0.1
  tmdb_api: ^1.0.1-stable
  video_player: ^0.10.8+1
  transparent_image: ^1.0.0
  animated_text_kit: ^2.2.0
  flutter_native_timezone: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - locale/
  # fonts:
  #   - family: Ionicons
  #     fonts:
  #       - asset: fonts/Ionicons.ttf
  #   - family: AntDesign
  #     fonts:
  #       - asset: fonts/AntDesign.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
